spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&useSSL=false
    username: root
    password: tiger
  jpa:
      show-sql: true
  session:
    store-type: none
server:
  port: 8000
yun:
  security:
    browser:
      loginType: JSON

#security:
#  basic:
#    enabled: false

#yun:
#  security:
#    browser:
#      loginPage: /demo-login.html